- job/errors.go
> missing argument for Sprintf()

- job-runner/api/api.go
- job-runner/chain/chain.go
- job-runner/chain/chain_test.go
- job-runner/chain/traverser.go
- job-runner/chain/traverser_test.go
- proto/s2s.go
jobData should be passed from job to job through the chain (as opposed to being a global map that all jobs in a chain share)
> Mf job data

- job-runner/chain/reaper.go
- job-runner/chain/traverser.go
- request-manager/request/manager.go
- request-manager/request/resumer.go
just a couple of changes to the logging, and a small bug in traverser.Stop
> Better logging + fix traverser Stop

- request-manager/request/manager.go
- request-manager/request/manager_test.go
- request-manager/resources/request_manager_schema.sql
Fix indention in request_manager_schema.sql
> Set proto.Request.Params post-grapher in request.Manager

- job-runner/runner/runner.go
- job-runner/runner/runner_test.go
Recover from a panic in job.Run(). Panics are treated like any other job failure - the job + sequence are retried as normal.
> Recover from job panics

- request-manager/api/api.go
- request-manager/api/api_test.go
- request-manager/request/manager.go
- request-manager/request/manager_test.go
- spinc/cmd/ps.go
- test/mock/request.go
Also, sort the request args listed in `spinc ps -v`
> Return request parameters + job chain with Get request

- request-manager/grapher/grapher_test.go
- request-manager/test/specs/cond-args-001.yaml
- test/mock/idgen.go
Thought there might be bug using optional arg for conditional sequence, but there's not: tested and working.
> Test grapher conditional sequence with optional arg

- request-manager/grapher/grapher.go
> make sure if arg has been set before building a conditional node

- spinc/cmd/running.go
> Handle STATE_SUSPENDED in spinc running command

- request-manager/request/manager.go
- version/version.go
> Retry starting job chain in request manager

- request-manager/request/manager.go
- version/version.go
> Fix to issue 121 fix

- request-manager/grapher/grapher.go
- request-manager/grapher/grapher_test.go
- request-manager/grapher/spec.go
- request-manager/test/specs/cond-args-001.yaml
- request-manager/test/specs/opt-args-001.yaml
- request-manager/test/specs/spec-bad-optional.yaml
- request-manager/test/specs/spec-bad-static.yaml
> Error on empty static default arg in specs

- request-manager/api/api.go
- request-manager/api/api_test.go
- request-manager/request/manager.go
- request-manager/request/manager_test.go
- test/mock/request.go
- version/version.go
> Mark failed requests as failed

- job-runner/chain/traverser.go
- job-runner/chain/traverser_test.go
- proto/proto.go
- request-manager/grapher/graph.go
- request-manager/grapher/grapher.go
- request-manager/grapher/grapher_test.go
- request-manager/grapher/spec.go
- request-manager/request/manager.go
- request-manager/request/manager_test.go
- request-manager/test/specs/a-b-c.yaml
- request-manager/test/specs/spec-bad-retry-duration.yaml
- request-manager/test/specs/spec-bad-retry.yaml
- version/version.go
> Implement sequence retry wait

- request-manager/grapher/grapher.go
> Improve error message when job args are missing

- spinc/cmd/cmd.go
- spinc/cmd/find.go
- spinc/cmd/find_test.go
- spinc/cmd/help.go
> Add 'spinc find' command

- linter/linter.go
- request-manager/graph/graph.go
- request-manager/graph/graph_test.go
- request-manager/graph/grapher.go
- request-manager/graph/grapher_test.go
- request-manager/graph/noop.go
- request-manager/graph/resolver.go
- request-manager/graph/resolver_test.go
- request-manager/request/manager.go
- request-manager/request/manager_test.go
- request-manager/request/resumer_test.go
- request-manager/server/server.go
- test/mock/resolver.go
Part 2/? of spinc linter improvements
> Rename graph code variables+components

- request-manager/graph/graph.go
Update depth-first search algorithms in the hasCycles() and isConnected() grapher methods to keep track of visited nodes and skip them on future iterations. Previously we were iterating through every possible path in the graph, which is unnecessary.
This change greatly reduces the creation time of a graph. For example, a moderately complex graph with a few hundred jobs that used to take 4 minutes to create now takes less than 1 second.
> Update depth-first search algorithms

- docs/release-notes/index.md
Updated change notes to prep for the release of 2.0.6
> Release 2.0.6

- docs/release-notes/index.md
New release to address panic on --help and --version.
> Release v2.0.7

- docs/v2.0/api/endpoints.md
- proto/proto.go
- proto/proto_test.go
- request-manager/api/api.go
- request-manager/api/api_test.go
- request-manager/request/manager.go
- request-manager/request/manager_test.go
- request-manager/test/data/request-default.sql
- spinc/cmd/find.go
- spinc/cmd/find_test.go
Also update spinc cli find to work with the new filter.
> Update find endpoint to allow filtering by request args
